part of './gift_shop_search_bloc.dart';

class GiftShopSearchMapper {
  GiftShopSearchViewModel getViewModel() {
    return const GiftShopSearchViewModel(
      cellState: CellState.grid,
      gifts: _gifts,
    );
  }
}

const _gifts = <GiftContentViewModel>[
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy1.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '08/20/2000',
    stockState: StockState.inStock,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy4.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '09/20/2000',
    stockState: StockState.customOrdersOnly,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy5.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '10/20/2000',
    stockState: StockState.customOrdersOnly,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy2.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '11/20/2000',
    stockState: StockState.inStock,
    title: 'Gray, Navy & Burgundy Luxe Fleece Blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy3.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '08/20/2000',
    stockState: StockState.inStock,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy1.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '09/20/2000',
    stockState: StockState.inStock,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy1.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '10/20/2000',
    stockState: StockState.inStock,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy1.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '11/20/2000',
    stockState: StockState.inStock,
    title: 'Gray, Navy & Burgundy Luxe Fleece Blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy1.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '08/20/2000',
    stockState: StockState.inStock,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy1.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '09/20/2000',
    stockState: StockState.inStock,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy1.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '10/20/2000',
    stockState: StockState.inStock,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy1.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '11/20/2000',
    stockState: StockState.inStock,
    title: 'Gray, Navy & Burgundy Luxe Fleece Blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy1.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '08/20/2000',
    stockState: StockState.inStock,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy1.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '09/20/2000',
    stockState: StockState.inStock,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy3.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '10/20/2000',
    stockState: StockState.inStock,
    title: 'Cozy campfire blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
  GiftContentViewModel(
    author: 'Why knot?',
    imagePath: 'assets/general/toy2.jpg',
    category: GiftCategory.aroundTheHouse,
    postedDate: '11/20/2000',
    stockState: StockState.inStock,
    title: 'Gray, Navy & Burgundy Luxe Fleece Blanket',
    liked: false,
    cost: 15,
    country: 'Kentucky, USA',
  ),
];
