name: online_shop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-233.0.dev <3.0.0"

dependencies:
  chopper: 4.0.1
  get_it: ^7.1.3
  flutter_bloc: ^7.1.0
  freezed_annotation: ^0.14.3
  flutter:
    sdk: flutter
  json_annotation: ^4.1.0
  meta: 1.7.0
  shared_preferences: ^2.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.3

dev_dependencies:
  build_runner: ^2.1.2
  chopper_generator: 4.0.2
  flutter_test:
    sdk: flutter
  freezed: 0.14.5
  http: ^0.13.0
  json_serializable: 5.0.2
  # swagger_dart_code_generator: 2.2.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/login/
