name: online_shop
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  reactive_value:
    path: ./packages/reactive_value

  chopper: 4.0.1
  get_it: ^7.1.3
  intl: ^0.17.0
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  flutter:
    sdk: flutter
  flutter_i18n: ^0.31.1
  flutter_staggered_grid_view: ^0.6.2
  json_annotation: ^4.4.0
  meta: ^1.7.0
  
  shared_preferences: ^2.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.3

dev_dependencies:
  build_runner: ^2.1.10
  flutter_test:
    sdk: flutter
  freezed: 2.1.0
  http: ^0.13.0
  json_serializable: 6.3.1
  # swagger_dart_code_generator: 2.2.0
  flutter_lints: ^1.0.0
  flutter_localizations:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/login/
    - assets/home/
    - assets/general/
